/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/borrow/{userId}/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a user's loans */
        get: operations["getLoansForUser"];
        put?: never;
        /**
         * Create a loan
         * @description Creates a USDT loan secured by the supplied collateral.
         */
        post: operations["createLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/borrow/loans/{loanId}/repay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Repay a loan
         * @description Marks an active loan as repaid and unlocks its collateral.
         */
        post: operations["repayLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and obtain a 24-hour JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Parameters for creating a collateralized USDT loan */
        CreateLoanRequest: {
            /**
             * @description Asset to lock as collateral
             * @example BTC
             * @enum {string}
             */
            collateralAsset: "BTC" | "ETH" | "USDT" | "USDC";
            /**
             * @description Amount of collateral to lock
             * @example 0.5
             */
            collateralAmount: number;
            /**
             * @description USDT amount to borrow
             * @example 15000
             */
            borrowedAmount: number;
        };
        /** @description A borrow position */
        LoanResponse: {
            /**
             * Format: int64
             * @example 42
             */
            id?: number;
            /**
             * @example BTC
             * @enum {string}
             */
            collateralAsset?: "BTC" | "ETH" | "USDT" | "USDC";
            /** @example 0.5 */
            collateralAmount?: number;
            /** @example 15000 */
            borrowedAmount?: number;
            /**
             * @example USDT
             * @enum {string}
             */
            borrowedAsset?: "BTC" | "ETH" | "USDT" | "USDC";
            /**
             * @description Annual percentage rate
             * @example 0
             */
            interestRateApr?: number;
            /**
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "REPAID" | "LIQUIDATED";
            /**
             * Format: date-time
             * @example 2026-08-30T12:00:00Z
             */
            createdAt?: string;
        };
        /** @description Standard API error response */
        ApiErrorResponse: {
            /**
             * Format: date-time
             * @example 2026-08-30T12:00:00Z
             */
            timestamp?: string;
            /**
             * Format: int32
             * @example 400
             */
            status?: number;
            /** @example Bad Request */
            error?: string;
            /** @example Insufficient available collateral balance */
            message?: string;
            /** @example /api/borrow/1/loans */
            path?: string;
        };
        /** @description Registration credentials */
        RegisterRequest: {
            /**
             * Format: email
             * @example satoshi@example.com
             */
            email: string;
            /** @example correct-horse-battery-staple */
            password: string;
        };
        /** @description Login credentials */
        LoginRequest: {
            /**
             * Format: email
             * @example satoshi@example.com
             */
            email: string;
            /** @example correct-horse-battery-staple */
            password: string;
        };
        /** @description Successful authentication result */
        AuthResponse: {
            /**
             * @description Bearer token valid for 24 hours
             * @example eyJhbGciOiJIUzI1NiJ9...
             */
            token?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLoansForUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loans returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoanResponse"][];
                };
            };
            /** @description Invalid user id or user not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    createLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLoanRequest"];
            };
        };
        responses: {
            /** @description Loan created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoanResponse"];
                };
            };
            /** @description Invalid input, insufficient collateral, or LTV limit exceeded */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    repayLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loanId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loan repaid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoanResponse"];
                };
            };
            /** @description Invalid loan id or loan not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Loan cannot be repaid in its current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid registration data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email is already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
}
