/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/wallet/{userId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw an available asset from a user's wallet */
        post: operations["withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/{userId}/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deposit an asset into a user's wallet */
        post: operations["deposit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/borrow/{userId}/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a user's loans */
        get: operations["getLoansForUser"];
        put?: never;
        /**
         * Create a loan
         * @description Creates a USDT loan secured by the supplied collateral.
         */
        post: operations["createLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/borrow/loans/{loanId}/repay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Repay a loan
         * @description Marks an active loan as repaid and unlocks its collateral.
         */
        post: operations["repayLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and obtain a 24-hour JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/{userId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a user's transactions
         * @description Returns newest transactions first.
         */
        get: operations["getTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/{userId}/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a user's wallet balances */
        get: operations["getBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Wallet deposit or withdrawal request */
        WalletTransactionRequest: {
            /**
             * @description Asset to deposit or withdraw
             * @example USDT
             * @enum {string}
             */
            asset: "BTC" | "ETH" | "USDT" | "USDC";
            /**
             * @description Positive asset amount
             * @example 250
             */
            amount: number;
        };
        /** @description Balance for one wallet asset */
        WalletBalanceResponse: {
            /**
             * @example BTC
             * @enum {string}
             */
            asset?: "BTC" | "ETH" | "USDT" | "USDC";
            /** @example 0.75 */
            availableAmount?: number;
            /** @example 0.25 */
            lockedAmount?: number;
        };
        /** @description Standard API error response */
        ApiErrorResponse: {
            /**
             * Format: date-time
             * @example 2026-08-30T12:00:00Z
             */
            timestamp?: string;
            /**
             * Format: int32
             * @example 400
             */
            status?: number;
            /** @example Bad Request */
            error?: string;
            /** @example Insufficient available collateral balance */
            message?: string;
            /** @example /api/borrow/1/loans */
            path?: string;
        };
        /** @description Parameters for creating a collateralized USDT loan */
        CreateLoanRequest: {
            /**
             * @description Asset to lock as collateral
             * @example BTC
             * @enum {string}
             */
            collateralAsset: "BTC" | "ETH" | "USDT" | "USDC";
            /**
             * @description Amount of collateral to lock
             * @example 0.5
             */
            collateralAmount: number;
            /**
             * @description USDT amount to borrow
             * @example 15000
             */
            borrowedAmount: number;
        };
        /** @description A borrow position */
        LoanResponse: {
            /**
             * Format: int64
             * @example 42
             */
            id?: number;
            /**
             * @example BTC
             * @enum {string}
             */
            collateralAsset?: "BTC" | "ETH" | "USDT" | "USDC";
            /** @example 0.5 */
            collateralAmount?: number;
            /** @example 15000 */
            borrowedAmount?: number;
            /**
             * @example USDT
             * @enum {string}
             */
            borrowedAsset?: "BTC" | "ETH" | "USDT" | "USDC";
            /**
             * @description Annual percentage rate
             * @example 0
             */
            interestRateApr?: number;
            /**
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "REPAID" | "LIQUIDATED";
            /**
             * Format: date-time
             * @example 2026-08-30T12:00:00Z
             */
            createdAt?: string;
        };
        /** @description Registration credentials */
        RegisterRequest: {
            /**
             * Format: email
             * @example satoshi@example.com
             */
            email: string;
            /** @example correct-horse-battery-staple */
            password: string;
        };
        /** @description Login credentials */
        LoginRequest: {
            /**
             * Format: email
             * @example satoshi@example.com
             */
            email: string;
            /** @example correct-horse-battery-staple */
            password: string;
        };
        /** @description Successful authentication result */
        AuthResponse: {
            /**
             * @description Bearer token valid for 24 hours
             * @example eyJhbGciOiJIUzI1NiJ9...
             */
            token?: string;
        };
        /** @description Wallet or account transaction */
        TransactionResponse: {
            /**
             * @example DEPOSIT
             * @enum {string}
             */
            type?: "DEPOSIT" | "WITHDRAW" | "BORROW" | "REPAY" | "EARN_SUBSCRIBE" | "EARN_WITHDRAW";
            /**
             * @example USDT
             * @enum {string}
             */
            asset?: "BTC" | "ETH" | "USDT" | "USDC";
            /** @example 250 */
            amount?: number;
            /**
             * @example COMPLETED
             * @enum {string}
             */
            status?: "PENDING" | "COMPLETED" | "FAILED";
            /**
             * Format: date-time
             * @example 2026-08-31T07:30:00Z
             */
            createdAt?: string;
        };
        /** @description Authenticated user profile */
        UserResponse: {
            /**
             * Format: int64
             * @example 1
             */
            id?: number;
            /** @example satoshi@example.com */
            email?: string;
            /**
             * @example VERIFIED
             * @enum {string}
             */
            kycStatus?: "NOT_STARTED" | "PENDING" | "VERIFIED";
            /**
             * Format: date-time
             * @example 2026-08-30T12:00:00Z
             */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletTransactionRequest"];
            };
        };
        responses: {
            /** @description Withdrawal completed and balance updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WalletBalanceResponse"];
                };
            };
            /** @description Invalid input or insufficient available balance */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing, invalid, or expired JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WalletBalanceResponse"];
                };
            };
            /** @description Authenticated user does not own this wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WalletBalanceResponse"];
                };
            };
        };
    };
    deposit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletTransactionRequest"];
            };
        };
        responses: {
            /** @description Deposit completed and balance updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WalletBalanceResponse"];
                };
            };
            /** @description Invalid user, asset, or amount */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing, invalid, or expired JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WalletBalanceResponse"];
                };
            };
            /** @description Authenticated user does not own this wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WalletBalanceResponse"];
                };
            };
        };
    };
    getLoansForUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loans returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoanResponse"][];
                };
            };
            /** @description Invalid user id or user not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Authenticated user does not own the requested account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    createLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLoanRequest"];
            };
        };
        responses: {
            /** @description Loan created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoanResponse"];
                };
            };
            /** @description Invalid input, insufficient collateral, or LTV limit exceeded */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Authenticated user does not own the requested account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    repayLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loanId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loan repaid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoanResponse"];
                };
            };
            /** @description Invalid loan id or loan not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Authenticated user does not own the loan */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Loan cannot be repaid in its current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid registration data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email is already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    getTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transactions returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"][];
                };
            };
            /** @description Invalid user id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing, invalid, or expired JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"][];
                };
            };
            /** @description Authenticated user does not own this wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"][];
                };
            };
        };
    };
    getBalances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balances returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WalletBalanceResponse"][];
                };
            };
            /** @description Invalid user id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Missing, invalid, or expired JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Authenticated user does not own the requested wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing, invalid, or expired JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
}
